name: mashatel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^2.3.1
  localize_and_translate: ^3.0.2
  string_validator: ^0.1.4
  flutter_svg: ^0.18.0
  cached_network_image: ^2.3.1
  carousel_slider: ^2.2.1
  google_fonts: ^1.1.0
  settings_ui: ^0.4.0
  image_picker: ^0.6.7+7
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.10
  time: "^1.3.0"
  equatable: ^1.2.5
  flutter_slidable: ^0.5.7
  flare_flutter: ^2.0.6
  auto_size_text: ^2.1.0
  connectivity: ^0.4.9+2
  get: ^3.11.1
  firebase_core: "^0.5.1"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"
  firebase_storage: "^4.0.0"
  geolocator: ^6.0.0+4
  google_maps_flutter: ^0.5.33
  progress_dialog: ^1.2.0
  provider: ^4.3.2+2
  after_layout: ^1.0.7+2
  url_launcher: ^5.7.2
  multi_image_picker: ^4.7.14
  file_picker: ^2.0.6
  dio: ^3.0.10
  http: ^0.12.2
  http_parser: ^3.1.4
  shimmer: ^1.1.2
  logger: ^0.9.4
  flutter_staggered_grid_view: ^0.3.2
  firebase_messaging: "^8.0.0-dev.5"
  flutter_local_notifications: ^3.0.1+2




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/langs/
    - assets/animations/
  #   - images/a_dot_ham.jpeg
fonts:
  - family: DIN NEXT ARABIC BOLD
    fonts:
      - asset: assets/fonts/DINNEXTARABICBOLD.otf
  - family: DIN NEXT ARABIC REGULAR
    fonts:
      - asset: assets/fonts/DINNEXTARABICREGULAR.otf
